### ISSUE TITLE
Links To The Actual Ontologies Don't Work

### ISSUE THREAD

**Issue by init-dcat-ap-de** [CommonCoreOntology/cco-webpage#10]
All links in the "Common Core Modules table" at https://commoncoreontology.github.io/cco-webpage/ point to https://commoncoreontology.github.io/cco-webpage/#

I would have expected to find the links to the ontologies there.

**Comment by johnbeve** [comment]
@oliviahobai would you mind updating the links on the cco-webpage so they point at the appropriate modules found here: https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/develop/src/cco-modules

Thank you @init-dcat-ap-de

**Comment by oliviahobai** [comment]
Should work on this branch here https://github.com/CommonCoreOntology/cco-webpage/blob/module-hyperlinks1/docs/index.md , where the title of each ontology now contains a hyperlink to its according .ttl file. Thanks for the suggestion

**Comment by johnbeve** [comment]
Fix merged here https://github.com/CommonCoreOntology/cco-webpage/pull/12
